# Generated by Django 5.0 on 2023-12-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_news_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="body_tag",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="body_tag_classes",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="image_tag",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="image_tag_classes",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
