# Generated by Django 5.0 on 2023-12-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_remove_post_image_post_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.JSONField(default=dict),
        ),
    ]
