# Generated by Django 5.0 on 2023-12-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_alter_post_link_to_news_alter_post_no_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="link_to_news",
            field=models.URLField(),
        ),
    ]
