# Generated by Django 5.0 on 2024-01-04 11:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_alter_post_link_to_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="audio",
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
