# Generated by Django 4.1 on 2024-01-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0020_post_find_all"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="find_all",
        ),
        migrations.AddField(
            model_name="source",
            name="find_all",
            field=models.BooleanField(default=True),
        ),
    ]
