# Generated by Django 4.1 on 2024-01-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0021_remove_post_find_all_source_find_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="audio_length",
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
