# Generated by Django 4.1 on 2024-01-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0024_post_has_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="audio_length",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
