# Generated by Django 4.1 on 2023-05-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newssource',
            old_name='site_url',
            new_name='news_url',
        ),
        migrations.AddField(
            model_name='newssource',
            name='site_domain',
            field=models.URLField(default='youtube.com', max_length=255),
            preserve_default=False,
        ),
    ]
