# Generated by Django 4.1 on 2024-01-11 13:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0023_rename_published_post_is_published_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video", cloudinary.models.CloudinaryField(max_length=255)),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "posts",
                    models.ManyToManyField(
                        blank=True, related_name="news", to="posts.post"
                    ),
                ),
            ],
            options={
                "ordering": ("-published_date",),
            },
        ),
    ]
