# Generated by Django 4.1 on 2024-01-11 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="published",
            new_name="is_published",
        ),
    ]
