# Generated by Django 5.0 on 2023-12-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_rename_content_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link_to_news",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
