# Generated by Django 5.0 on 2023-12-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_alter_post_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
