# Generated by Django 5.0 on 2023-12-23 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_post_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="active",
            new_name="no_body",
        ),
    ]
