# Generated by Django 5.0 on 2023-12-25 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_rename_active_post_no_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="body_tag_classes",
            new_name="body_tag_class",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="html_tag_classes",
            new_name="html_tag_class",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="image_tag_classes",
            new_name="image_tag_class",
        ),
    ]
