# Generated by Django 5.0 on 2024-01-05 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0017_post_summarised"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="audio",
        ),
    ]
