# Generated by Django 4.1 on 2024-01-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0019_post_audio_post_no_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="find_all",
            field=models.BooleanField(default=True),
        ),
    ]
