# Generated by Django 5.0 on 2023-12-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscribers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=225),
        ),
    ]
