# Generated by Django 5.0 on 2023-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscribers", "0002_alter_subscriber_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=225, unique=True),
        ),
    ]
