# Generated by Django 5.0 on 2023-12-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_source_body_tag_source_body_tag_classes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.JSONField(default={}),
        ),
    ]
