# Generated by Django 5.0 on 2023-12-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_rename_html_tag_source_link_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="link_to_news",
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="no_body",
            field=models.BooleanField(default=True),
        ),
    ]
