# Generated by Django 5.0 on 2024-01-04 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_alter_post_link_to_news"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post",
            unique_together=set(),
        ),
    ]
