# Generated by Django 5.0 on 2024-01-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0014_alter_post_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="link_to_news",
            field=models.URLField(unique=True),
        ),
    ]
