# Generated by Django 4.1 on 2024-01-06 22:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0018_remove_post_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="audio",
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="no_audio",
            field=models.BooleanField(default=True),
        ),
    ]
